name: ci
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: pip install tox
      - name: Run linter
        run: make lint
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.x'
      - run: pip install tox
      - name: Build charm
        run: make build
      - name: Upload charm artifact
        uses: actions/upload-artifact@v1
        with:
          name: charm
          path: /tmp/charm-builds/alerta
  test:
    runs-on: ubuntu-18.04
    needs: build
    strategy:
      fail-fast: false
      matrix:
        juju_channel:
          - 2.5/stable
          - 2.6/stable
          - 2.7/stable
        test_bundles:
          - xenial-bundle
          - bionic-bundle
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.x'
      - run: pip install tox
      - name: Download charm artifact
        uses: actions/download-artifact@v1
        with:
          name: charm
          path: /tmp/charm-builds/alerta
      # Workarounds for https://github.com/actions/upload-artifact/issues/38
      - run: chmod +x -R /tmp/charm-builds/alerta/bin
      - run: chmod +x -R /tmp/charm-builds/alerta/hooks
      - name: Set up LXD
        run: |
          sudo usermod --append --groups lxd $(whoami)
          sudo su $(whoami) -c 'lxd init --auto'
          sudo su $(whoami) -c 'lxc network set lxdbr0 ipv6.address none'
      - name: Change ownership of root workaround for snapcraft
        # See https://forum.snapcraft.io/t/permissions-problem-using-snapcraft-in-azure-pipelines/13258/14?u=szeestraten
        run: sudo chown root:root /
      - name: Set up juju
        run: |
          sudo snap install juju --classic --channel=${{ matrix.juju_channel }}
          sudo su $(whoami) -c 'juju bootstrap localhost --no-gui'
      - name: Run deploy
        run: make deploy-${{ matrix.test_bundles }}
      - name: Run jujuna tests
        run: make test-${{ matrix.test_bundles }}
      - name: Display juju debug log on failure
        run: juju debug-log --lines 100
        if: failure()
